In [1]:
import pandas as pd #Importar libreria

In [3]:
df = pd.read_csv("vgsales.csv")  # Carga de datos y asignar variable

In [4]:
df["Rank"].diff().value_counts()

Rank
1.0    16595
2.0        2
Name: count, dtype: int64

In [5]:
df[df["Rank"].diff() != 1][["Rank", "Name"]]

        Rank               Name
0          1         Wii Sports
653      655           Monopoly
14198  14201  Monster Guardians

In [6]:
df.loc[648:656, ["Rank", "Name", "Global_Sales"]]

     Rank                                         Name  Global_Sales
648   649                               Theme Hospital          2.40
649   650     Frogger's Adventures: Temple of the Frog          2.39
650   651                        Need for Speed (2015)          2.39
651   652                                Zumba Fitness          2.39
652   653  LEGO Indiana Jones: The Original Adventures          2.39
653   655                                     Monopoly          2.39
654   656                       Batman: Arkham Origins          2.39
655   657                                  Dead Island          2.39
656   658                                  Guitar Hero          2.38

In [7]:
df[df["Rank"].diff() > 1][["Rank", "Name", "Global_Sales"]]

        Rank               Name  Global_Sales
653      655           Monopoly          2.39
14198  14201  Monster Guardians          0.03

In [8]:
df["Rank"] = range(1, len(df) + 1) # el dataset tenia un error ya que habia un salto en el ranking, con esta linea queda subsanado

In [9]:
df.loc[648:656, ["Rank", "Name"]]

     Rank                                         Name
648   649                               Theme Hospital
649   650     Frogger's Adventures: Temple of the Frog
650   651                        Need for Speed (2015)
651   652                                Zumba Fitness
652   653  LEGO Indiana Jones: The Original Adventures
653   654                                     Monopoly
654   655                       Batman: Arkham Origins
655   656                                  Dead Island
656   657                                  Guitar Hero

In [10]:
df["Rank"].is_unique

True

In [11]:
# Dimensiones del dataset
df.shape

(16598, 11)

In [12]:
# Información general: columnas, tipos de datos y valores nulos
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16598 entries, 0 to 16597
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Rank          16598 non-null  int64
 1   Name          16598 non-null  object
 2   Platform      16598 non-null  object
 3   Year          16327 non-null  float64
 4   Genre         16598 non-null  object
 5   Publisher     16540 non-null  object
 6   NA_Sales      16598 non-null  float64
 7   EU_Sales      16598 non-null  float64
 8   JP_Sales      16598 non-null  float64
 9   Other_Sales   16598 non-null  float64
 10  Global_Sales  16598 non-null  float64
dtypes: float64(6), int64(1), object(4)
memory usage: 1.4+ MB

In [13]:

# Resumen estadístico de las variables numéricas
df.describe()

,Rank,Year,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
count,16598.000000,16327.000000,16598.000000,16598.000000,16598.000000,16598.000000,16598.000000
mean,8299.500000,2006.406443,0.264667,0.146652,0.077782,0.048063,0.537441
std,4791.574219,5.828981,0.816683,0.505351,0.309291,0.188588,1.555028
min,1.000000,1980.000000,0.000000,0.000000,0.000000,0.000000,0.010000
25%,4150.250000,2003.000000,0.000000,0.000000,0.000000,0.000000,0.060000
50%,8299.500000,2007.000000,0.080000,0.020000,0.000000,0.010000,0.170000
75%,12448.750000,2010.000000,0.240000,0.110000,0.040000,0.040000,0.470000
max,16598.000000,2020.000000,41.490000,29.020000,10.220000,10.570000,82.740000

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16598 entries, 0 to 16597
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Rank          16598 non-null  int64
 1   Name          16598 non-null  object
 2   Platform      16598 non-null  object
 3   Year          16327 non-null  float64
 4   Genre         16598 non-null  object
 5   Publisher     16540 non-null  object
 6   NA_Sales      16598 non-null  float64
 7   EU_Sales      16598 non-null  float64
 8   JP_Sales      16598 non-null  float64
 9   Other_Sales   16598 non-null  float64
 10  Global_Sales  16598 non-null  float64
dtypes: float64(6), int64(1), object(4)
memory usage: 1.4+ MB

In [15]:
df.isnull().sum() #Comprobamos las columnas que contienen valores nulos y nos diga el total

Rank              0
Name              0
Platform          0
Year            271
Genre             0
Publisher        58
NA_Sales          0
EU_Sales          0
JP_Sales          0
Other_Sales       0
Global_Sales      0
dtype: int64

In [23]:
df[df["Year"].isnull()] #PEdimos las filas que tengan valor nulo en year

Empty DataFrame
Columns: [Rank, Name, Platform, Year, Genre, Publisher, NA_Sales, EU_Sales, JP_Sales, Other_Sales, Global_Sales]
Index: []

In [24]:
df[df["Publisher"].isnull()] #Pedimos las filas que tienen valor nulo en Publisher

Empty DataFrame
Columns: [Rank, Name, Platform, Year, Genre, Publisher, NA_Sales, EU_Sales, JP_Sales, Other_Sales, Global_Sales]
Index: []

In [18]:
df["Genre"].unique() #lista de géneros

array(['Sports', 'Platform', 'Racing', 'Role-Playing', 'Puzzle', 'Misc',
       'Shooter', 'Simulation', 'Action', 'Fighting', 'Adventure',
       'Strategy'], dtype=object)

In [19]:
df_shooter = df[df["Genre"] == "Shooter"] #DataFrame de Shooter

In [20]:
df_shooter #Enseñar filas correspondientes a shooter

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
9,10,Duck Hunt,NES,1984.0,Shooter,Nintendo,26.93,0.63,0.28,0.47,28.31
29,30,Call of Duty: Modern Warfare 3,X360,2011.0,Shooter,Activision,9.03,4.28,0.13,1.32,14.76
31,32,Call of Duty: Black Ops,X360,2010.0,Shooter,Activision,9.67,3.73,0.11,1.13,14.64
33,34,Call of Duty: Black Ops 3,PS4,2015.0,Shooter,Activision,5.77,5.81,0.35,2.31,14.24
34,35,Call of Duty: Black Ops II,PS3,2012.0,Shooter,Activision,4.99,5.88,0.65,2.52,14.03
...,...,...,...,...,...,...,...,...,...,...,...
16501,16502,"Transformers: War for Cybertron (XBox 360, PS3...",PC,2010.0,Shooter,Activision,0.01,0.00,0.00,0.00,0.01
16569,16570,Resident Evil 4 HD,XOne,2016.0,Shooter,Capcom,0.01,0.00,0.00,0.00,0.01
16577,16578,Damnation,PC,2009.0,Shooter,Codemasters,0.00,0.01,0.00,0.00,0.01
16585,16586,Breach,PC,2011.0,Shooter,Destineer,0.01,0.00,0.00,0.00,0.01
16594,16595,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.00,0.01

In [21]:
df = df.fillna("No consta") #Cambiar todos los valores nulos por "No consta"

In [22]:
df.isna().sum() #Comprobar si quedan valores nulos

Rank            0
Name            0
Platform        0
Year            0
Genre           0
Publisher       0
NA_Sales        0
EU_Sales        0
JP_Sales        0
Other_Sales     0
Global_Sales    0
dtype: int64